// src-tauri/src/db/schema/links.rs

use super::Migration;

pub const SCHEMA_SQL: &[&str] = &[
    // ── links ─────────────────────────────────────────────────────────────────
    r#"CREATE TABLE IF NOT EXISTS links (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL,
    media_id TEXT,
    category_id TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    order_index INTEGER DEFAULT 0,
    is_active INTEGER DEFAULT 1,
    created_at INTEGER DEFAULT (strftime('%s','now')),
    updated_at INTEGER DEFAULT (strftime('%s','now')),
    keywords TEXT DEFAULT '',
    hidden_from_profile INTEGER DEFAULT 0,
    sale_price TEXT,
    price TEXT,
    button_text TEXT,
    location TEXT,
    date TEXT,
    collection_name TEXT,
    video_url TEXT,
    logo_url TEXT,
    post_url TEXT,
    platform_name TEXT,
    collection_id TEXT,
    slug TEXT UNIQUE,
    in_app INTEGER NOT NULL DEFAULT 0,
    geo_redirect TEXT NOT NULL DEFAULT '{}'
  )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_links_profile_id ON links (profile_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_links_category_id ON links (category_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_links_collection_id ON links (collection_id)"#,
    // ── link_analytics ────────────────────────────────────────────────────────
    r#"CREATE TABLE IF NOT EXISTS link_analytics (
    id TEXT PRIMARY KEY,
    link_id TEXT NOT NULL UNIQUE,
    profile_id TEXT NOT NULL,
    total_clicks INTEGER DEFAULT 0,
    device_clicks TEXT DEFAULT '{}',
    os_clicks TEXT DEFAULT '{}',
    browser_clicks TEXT DEFAULT '{}',
    country_clicks TEXT DEFAULT '{}',
    city_clicks TEXT DEFAULT '{}',
    referrer_clicks TEXT DEFAULT '{}',
    clicks_lifetime TEXT DEFAULT '{}',
    clicks_24h TEXT DEFAULT '[]',
    clicks_7d TEXT DEFAULT '[]',
    clicks_30d TEXT DEFAULT '[]',
    clicks_12m TEXT DEFAULT '[]',
    utm_source_clicks TEXT DEFAULT '{}',
    utm_medium_clicks TEXT DEFAULT '{}',
    utm_campaign_clicks TEXT DEFAULT '{}',
    created_at INTEGER DEFAULT (strftime('%s','now')),
    updated_at INTEGER DEFAULT (strftime('%s','now')),
    last_aggregated_at INTEGER DEFAULT 0,
    bot_clicks INTEGER DEFAULT 0
  )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_link_analytics_link_id ON link_analytics (link_id)"#,
    // ── link_analytics_by_category (1 row/category per profile) ──
    r#"CREATE TABLE IF NOT EXISTS link_analytics_by_category (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL,
    category_id TEXT NOT NULL,
    total_links INTEGER NOT NULL DEFAULT 0,
    active_links INTEGER NOT NULL DEFAULT 0,
    total_clicks INTEGER NOT NULL DEFAULT 0,
    bot_clicks INTEGER NOT NULL DEFAULT 0,
    bot_views INTEGER NOT NULL DEFAULT 0,
    total_views INTEGER NOT NULL DEFAULT 0,
    bot_visits INTEGER NOT NULL DEFAULT 0,
    total_visits INTEGER NOT NULL DEFAULT 0,
    views_device_breakdown TEXT NOT NULL DEFAULT '{}',
    views_os_breakdown TEXT NOT NULL DEFAULT '{}',
    views_browser_breakdown TEXT NOT NULL DEFAULT '{}',
    views_country_breakdown TEXT NOT NULL DEFAULT '{}',
    views_city_breakdown TEXT NOT NULL DEFAULT '{}',
    views_referrer_breakdown TEXT NOT NULL DEFAULT '{}',
    views_7d TEXT NOT NULL DEFAULT '[]',
    views_30d TEXT NOT NULL DEFAULT '[]',
    views_12m TEXT NOT NULL DEFAULT '[]',
    views_lifetime TEXT NOT NULL DEFAULT '{}',
    visits_device_breakdown TEXT NOT NULL DEFAULT '{}',
    visits_os_breakdown TEXT NOT NULL DEFAULT '{}',
    visits_browser_breakdown TEXT NOT NULL DEFAULT '{}',
    visits_country_breakdown TEXT NOT NULL DEFAULT '{}',
    visits_city_breakdown TEXT NOT NULL DEFAULT '{}',
    visits_referrer_breakdown TEXT NOT NULL DEFAULT '{}',
    visits_7d TEXT NOT NULL DEFAULT '[]',
    visits_30d TEXT NOT NULL DEFAULT '[]',
    visits_12m TEXT NOT NULL DEFAULT '[]',
    visits_lifetime TEXT NOT NULL DEFAULT '{}',
    device_clicks TEXT NOT NULL DEFAULT '{}',
    os_clicks TEXT NOT NULL DEFAULT '{}',
    browser_clicks TEXT NOT NULL DEFAULT '{}',
    country_clicks TEXT NOT NULL DEFAULT '{}',
    city_clicks TEXT NOT NULL DEFAULT '{}',
    referrer_clicks TEXT NOT NULL DEFAULT '{}',
    clicks_lifetime TEXT NOT NULL DEFAULT '{}',
    clicks_7d TEXT NOT NULL DEFAULT '[]',
    clicks_30d TEXT NOT NULL DEFAULT '[]',
    clicks_12m TEXT NOT NULL DEFAULT '[]',
    last_aggregated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    UNIQUE(profile_id, category_id)
  )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_link_analytics_by_category_profile ON link_analytics_by_category (profile_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_link_analytics_by_category_category ON link_analytics_by_category (category_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_link_analytics_profile_id ON link_analytics (profile_id)"#,
    // ── clicks_analytics (raw append-only, one row per click, aggregated into link_analytics) ──
    r#"CREATE TABLE IF NOT EXISTS clicks_analytics (
    id TEXT PRIMARY KEY,
    link_id TEXT NOT NULL,
    profile_id TEXT NOT NULL,
    device TEXT,
    os TEXT,
    browser TEXT,
    country TEXT,
    city TEXT,
    referrer TEXT,
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    clicked_at INTEGER DEFAULT (strftime('%s','now')),
    is_bot INTEGER DEFAULT 0
  )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_clicks_analytics_link_id ON clicks_analytics (link_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_clicks_analytics_profile_id ON clicks_analytics (profile_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_clicks_analytics_clicked_at ON clicks_analytics (clicked_at)"#,
    // P1-3: composite index for retention + aggregation queries (profile+time)
    r#"CREATE INDEX IF NOT EXISTS idx_clicks_profile_time ON clicks_analytics (profile_id, clicked_at)"#,
    // ── link_pages (per-category SEO settings — replaces old collections purpose) ──
    r#"CREATE TABLE IF NOT EXISTS link_pages (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL,
    media_id TEXT,
    category_id TEXT,
    category_slug TEXT NOT NULL,
    seo_title TEXT,
    seo_description TEXT,
    seo_og_image TEXT,
    seo_robots TEXT,
    seo_block_indexing INTEGER NOT NULL DEFAULT 0,
    title TEXT,
    description TEXT,
    ads_code_sidebar TEXT,
    ads_code_top TEXT,
    ads_code_bottom TEXT,
    published INTEGER NOT NULL DEFAULT 1,
    hidden INTEGER NOT NULL DEFAULT 0,
    image_ads TEXT DEFAULT NULL,
    is_active INTEGER NOT NULL DEFAULT 0,
    nav_active INTEGER NOT NULL DEFAULT 1,
    menu_active INTEGER NOT NULL DEFAULT 1,
    footer_active INTEGER NOT NULL DEFAULT 1,
    section TEXT DEFAULT NULL,
    created_at INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    updated_at INTEGER NOT NULL DEFAULT (strftime('%s','now'))
  )"#,
    r#"CREATE UNIQUE INDEX IF NOT EXISTS idx_link_pages_profile_cat ON link_pages (profile_id, category_slug)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_link_pages_profile_id ON link_pages (profile_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_link_pages_category_id ON link_pages (category_id)"#,
];

pub const MIGRATIONS_SQL: &[Migration] = &[];
