use super::Migration;

pub const SCHEMA_SQL: &[&str] = &[
    // ── products (51 cols) ────────────────────────────────────────────────────
    r#"CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    
    profile_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    updated_by TEXT,
    category_id TEXT,
    collection_id TEXT,
    community_id TEXT,
    parent_id TEXT,
    
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    slug TEXT UNIQUE,
    excerpt TEXT,
    description TEXT,
    ai_summary TEXT,
    
    price_cents INTEGER NOT NULL DEFAULT 0,
    sale_price_cents INTEGER,
    tax_inclusive INTEGER NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'usd',
    
    media_id TEXT,
    slider_id TEXT,
    thumbnail_url TEXT,
    hero_image_url TEXT,
    hero_video_url TEXT,
    cover_video_url TEXT,
    media_url TEXT DEFAULT '[]',
    file_url TEXT,
    
    is_active INTEGER NOT NULL DEFAULT 1,
    published INTEGER NOT NULL DEFAULT 0,
    hidden INTEGER NOT NULL DEFAULT 0,
    archived INTEGER NOT NULL DEFAULT 0,
    visibility TEXT NOT NULL DEFAULT 'published',
    order_index INTEGER DEFAULT 0,
    is_featured INTEGER NOT NULL DEFAULT 0,
    hide_author INTEGER NOT NULL DEFAULT 0,
    
    date INTEGER,
    published_at INTEGER,
    archived_at INTEGER,
    cta_clicks INTEGER NOT NULL DEFAULT 0,
    max_sales INTEGER,
    show_total_sales INTEGER NOT NULL DEFAULT 0,
    
    external_product_id TEXT,
    forms_id TEXT,
    lessons TEXT,
    total_lessons INTEGER NOT NULL DEFAULT 0,
    course_access_type TEXT DEFAULT 'open',
    course_access_config TEXT DEFAULT '{}',
    
    add_people TEXT DEFAULT '[]',
    location TEXT,
    location_map TEXT,
    timezone TEXT,
    
    duration_minutes INTEGER,
    calendar_link TEXT,
    scheduling_provider TEXT,
    scheduling_metadata TEXT,
    
    webinar_link TEXT,
    webinar_platform TEXT,
    webinar_schedule TEXT,
    
    billing_interval TEXT,
    features TEXT,
    tags TEXT,
    
    settings TEXT,
    meeting_settings TEXT,
    webinar_settings TEXT,
    event_settings TEXT,
    service_settings TEXT,
    listing_settings TEXT,
    booking_settings TEXT,
    sponsorship_settings TEXT,
    additional_details TEXT DEFAULT '[]',
    sections TEXT NOT NULL DEFAULT '[]',
    hide_default_sections INTEGER NOT NULL DEFAULT 0,
    
    button_text TEXT,
    cta_button TEXT DEFAULT '{}',
    up_sell TEXT DEFAULT '[]',
    confirmation_email_subject TEXT,
    confirmation_email_body TEXT,
    image_ads TEXT DEFAULT NULL,
    unit INTEGER DEFAULT NULL,
    product_rating TEXT DEFAULT '{"total_ratings":0,"star_5":0,"star_4":0,"star_3":0,"star_2":0,"star_1":0,"average":0,"recent_reviews":[]}',
    
    seo_title TEXT,
    seo_description TEXT,
    seo_og_image TEXT,
    seo_robots TEXT,
    seo_block_indexing INTEGER NOT NULL DEFAULT 0,
    
    platform_name TEXT,
    platform_url TEXT,
    post_frequency TEXT,
    
    created_at INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    updated_at INTEGER NOT NULL DEFAULT (strftime('%s','now'))
  )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_products_profile ON products (profile_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_products_user ON products (user_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_products_updated_by ON products (profile_id, updated_by)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_products_parent ON products (profile_id, parent_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_products_tax_inclusive ON products (profile_id, tax_inclusive)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_products_type ON products (type)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_products_category ON products (category_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_products_collection_id ON products (collection_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_products_date ON products (date)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_products_cta_clicks ON products (cta_clicks)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_products_archived ON products (profile_id, archived)"#,
    // ── product_analytics ─────────────────────────────────────────────────────
    r#"CREATE TABLE IF NOT EXISTS product_analytics (
    id TEXT PRIMARY KEY,
    product_id TEXT NOT NULL UNIQUE,
    profile_id TEXT NOT NULL,
    
    bot_views INTEGER NOT NULL DEFAULT 0,
    total_views INTEGER NOT NULL DEFAULT 0,
    views_7d TEXT NOT NULL DEFAULT '[]',
    views_30d TEXT NOT NULL DEFAULT '[]',
    views_12m TEXT NOT NULL DEFAULT '[]',
    views_lifetime TEXT NOT NULL DEFAULT '{}',
    views_device_breakdown TEXT NOT NULL DEFAULT '{}',
    views_os_breakdown TEXT NOT NULL DEFAULT '{}',
    views_browser_breakdown TEXT NOT NULL DEFAULT '{}',
    views_country_breakdown TEXT NOT NULL DEFAULT '{}',
    views_city_breakdown TEXT NOT NULL DEFAULT '{}',
    views_referrer_breakdown TEXT NOT NULL DEFAULT '{}',
    
    bot_visits INTEGER NOT NULL DEFAULT 0,
    total_visits INTEGER NOT NULL DEFAULT 0,
    visits_7d TEXT NOT NULL DEFAULT '[]',
    visits_30d TEXT NOT NULL DEFAULT '[]',
    visits_12m TEXT NOT NULL DEFAULT '[]',
    visits_lifetime TEXT NOT NULL DEFAULT '{}',
    visits_device_breakdown TEXT NOT NULL DEFAULT '{}',
    visits_os_breakdown TEXT NOT NULL DEFAULT '{}',
    visits_browser_breakdown TEXT NOT NULL DEFAULT '{}',
    visits_country_breakdown TEXT NOT NULL DEFAULT '{}',
    visits_city_breakdown TEXT NOT NULL DEFAULT '{}',
    visits_referrer_breakdown TEXT NOT NULL DEFAULT '{}',
    
    total_sales INTEGER NOT NULL DEFAULT 0,
    sales_7d TEXT NOT NULL DEFAULT '[]',
    sales_30d TEXT NOT NULL DEFAULT '[]',
    sales_12m TEXT NOT NULL DEFAULT '[]',
    sales_lifetime TEXT NOT NULL DEFAULT '{}',
    sales_device_breakdown TEXT NOT NULL DEFAULT '{}',
    sales_os_breakdown TEXT NOT NULL DEFAULT '{}',
    sales_browser_breakdown TEXT NOT NULL DEFAULT '{}',
    sales_country_breakdown TEXT NOT NULL DEFAULT '{}',
    sales_city_breakdown TEXT NOT NULL DEFAULT '{}',
    sales_referrer_breakdown TEXT NOT NULL DEFAULT '{}',
    sales_utm_source TEXT NOT NULL DEFAULT '{}',
    sales_utm_medium TEXT NOT NULL DEFAULT '{}',
    sales_utm_campaign TEXT NOT NULL DEFAULT '{}',
    
    total_revenue_cents INTEGER NOT NULL DEFAULT 0,
    revenue_7d TEXT NOT NULL DEFAULT '[]',
    revenue_30d TEXT NOT NULL DEFAULT '[]',
    revenue_12m TEXT NOT NULL DEFAULT '[]',
    revenue_lifetime TEXT NOT NULL DEFAULT '{}',
    
    email_opens INTEGER NOT NULL DEFAULT 0,
    email_clicks INTEGER NOT NULL DEFAULT 0,
    last_aggregated_at INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    updated_at INTEGER NOT NULL DEFAULT (strftime('%s','now'))
  )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_product_analytics_product_id ON product_analytics (product_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_product_analytics_profile_id ON product_analytics (profile_id)"#,
    // ── purchases ─────────────────────────────────────────────────────────────
    r#"CREATE TABLE IF NOT EXISTS purchases (
    id TEXT PRIMARY KEY,
    
    profile_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    product_id TEXT NOT NULL,
    community_member_id TEXT,
    
    customer_name TEXT,
    email TEXT NOT NULL,
    buyer_avatar_url TEXT,
    
    transaction_id TEXT,
    amount_cents INTEGER NOT NULL,
    platform_fee_cents INTEGER NOT NULL,
    currency TEXT NOT NULL DEFAULT 'usd',
    payment_processor TEXT NOT NULL,
    payment_reference TEXT,
    payment_status TEXT NOT NULL DEFAULT 'completed',
    status TEXT NOT NULL DEFAULT 'active',
    refunded_at INTEGER,
    refund_reason TEXT,
    
    access_token TEXT NOT NULL UNIQUE,
    access_token_secret TEXT,
    access_token_expires_at INTEGER,
    last_accessed_at INTEGER,
    access_count INTEGER NOT NULL DEFAULT 0,
    
    rating_star INTEGER,
    rating_review TEXT,
    rated_at INTEGER,
    rating_reply TEXT,
    customer_message TEXT,
    
    device TEXT,
    os TEXT,
    browser TEXT,
    referrer TEXT,
    city TEXT,
    country TEXT,
    timezone TEXT,
    ip_address TEXT,
    user_agent TEXT,
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    
    course_progress TEXT,
    course_completed INTEGER NOT NULL DEFAULT 0,
    course_completion_date INTEGER,
    
    consultancy_scheduled_at INTEGER,
    consultancy_meeting_link TEXT,
    consultancy_status TEXT,
    slots TEXT,
    meeting_link TEXT,
    approval_status TEXT DEFAULT 'pending',
    
    subscription_id TEXT,
    subscription_status TEXT,
    subscription_current_period_end INTEGER,
    
    webinar_access_link TEXT,
    webinar_scheduled_at INTEGER,
    
    email_opened_at INTEGER,
    email_open_count INTEGER NOT NULL DEFAULT 0,
    email_clicked_at INTEGER,
    
    metadata TEXT,
    created_at INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    updated_at INTEGER NOT NULL DEFAULT (strftime('%s','now'))
  )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_purchases_profile ON purchases (profile_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_purchases_product ON purchases (product_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_purchases_email ON purchases (email)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_purchases_community_member_id ON purchases (community_member_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_purchases_user_id ON purchases (user_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_purchases_created_at ON purchases (created_at)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_purchases_status ON purchases (status)"#,
];

pub const MIGRATIONS_SQL: &[Migration] = &[];

pub const SEED_SQL: &[&str] = &[];
