/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectTeamRouteImport } from './routes/project-team'
import { Route as ProjectConnectorsRouteImport } from './routes/project-connectors'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectTeamRoute = ProjectTeamRouteImport.update({
  id: '/project-team',
  path: '/project-team',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectConnectorsRoute = ProjectConnectorsRouteImport.update({
  id: '/project-connectors',
  path: '/project-connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/connectors': typeof ConnectorsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/models': typeof ModelsRoute
  '/project-connectors': typeof ProjectConnectorsRoute
  '/project-team': typeof ProjectTeamRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/connectors': typeof ConnectorsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/models': typeof ModelsRoute
  '/project-connectors': typeof ProjectConnectorsRoute
  '/project-team': typeof ProjectTeamRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/connectors': typeof ConnectorsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/models': typeof ModelsRoute
  '/project-connectors': typeof ProjectConnectorsRoute
  '/project-team': typeof ProjectTeamRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/connectors'
    | '/login'
    | '/logout'
    | '/models'
    | '/project-connectors'
    | '/project-team'
    | '/settings'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/connectors'
    | '/login'
    | '/logout'
    | '/models'
    | '/project-connectors'
    | '/project-team'
    | '/settings'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/connectors'
    | '/login'
    | '/logout'
    | '/models'
    | '/project-connectors'
    | '/project-team'
    | '/settings'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  ConnectorsRoute: typeof ConnectorsRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ModelsRoute: typeof ModelsRoute
  ProjectConnectorsRoute: typeof ProjectConnectorsRoute
  ProjectTeamRoute: typeof ProjectTeamRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-team': {
      id: '/project-team'
      path: '/project-team'
      fullPath: '/project-team'
      preLoaderRoute: typeof ProjectTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-connectors': {
      id: '/project-connectors'
      path: '/project-connectors'
      fullPath: '/project-connectors'
      preLoaderRoute: typeof ProjectConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  ConnectorsRoute: ConnectorsRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ModelsRoute: ModelsRoute,
  ProjectConnectorsRoute: ProjectConnectorsRoute,
  ProjectTeamRoute: ProjectTeamRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
