CREATE TABLE `project_usage` (
	`id` text PRIMARY KEY NOT NULL,
	`tokens_prompt_lifetime` integer DEFAULT 0 NOT NULL,
	`tokens_prompt_cached_lifetime` integer DEFAULT 0 NOT NULL,
	`tokens_completion_lifetime` integer DEFAULT 0 NOT NULL,
	`tokens_reasoning_lifetime` integer DEFAULT 0 NOT NULL,
	`cost_lifetime_usd` real DEFAULT 0 NOT NULL,
	`sessions_lifetime` integer DEFAULT 0 NOT NULL,
	`cache_hits_lifetime` integer DEFAULT 0 NOT NULL,
	`analytics_lifetime` text DEFAULT '{}' NOT NULL,
	`usage_24h` text DEFAULT '[]' NOT NULL,
	`usage_7d` text DEFAULT '[]' NOT NULL,
	`usage_30d` text DEFAULT '[]' NOT NULL,
	`usage_12m` text DEFAULT '[]' NOT NULL,
	`by_model` text DEFAULT '{}' NOT NULL,
	`by_provider` text DEFAULT '{}' NOT NULL,
	`by_cli` text DEFAULT '{}' NOT NULL,
	`by_member` text DEFAULT '{}' NOT NULL,
	`by_project` text DEFAULT '{}' NOT NULL,
	`by_org` text DEFAULT '{}' NOT NULL,
	`heatmap_365d` text DEFAULT '{}' NOT NULL,
	`last_synced_at` text,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `org_usage` (
	`id` text PRIMARY KEY NOT NULL,
	`tokens_prompt_lifetime` integer DEFAULT 0 NOT NULL,
	`tokens_prompt_cached_lifetime` integer DEFAULT 0 NOT NULL,
	`tokens_completion_lifetime` integer DEFAULT 0 NOT NULL,
	`tokens_reasoning_lifetime` integer DEFAULT 0 NOT NULL,
	`cost_lifetime_usd` real DEFAULT 0 NOT NULL,
	`sessions_lifetime` integer DEFAULT 0 NOT NULL,
	`cache_hits_lifetime` integer DEFAULT 0 NOT NULL,
	`analytics_lifetime` text DEFAULT '{}' NOT NULL,
	`usage_24h` text DEFAULT '[]' NOT NULL,
	`usage_7d` text DEFAULT '[]' NOT NULL,
	`usage_30d` text DEFAULT '[]' NOT NULL,
	`usage_12m` text DEFAULT '[]' NOT NULL,
	`by_model` text DEFAULT '{}' NOT NULL,
	`by_provider` text DEFAULT '{}' NOT NULL,
	`by_cli` text DEFAULT '{}' NOT NULL,
	`by_member` text DEFAULT '{}' NOT NULL,
	`by_project` text DEFAULT '{}' NOT NULL,
	`by_org` text DEFAULT '{}' NOT NULL,
	`heatmap_365d` text DEFAULT '{}' NOT NULL,
	`last_synced_at` text,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `account_usage` (
	`id` text PRIMARY KEY NOT NULL,
	`tokens_prompt_lifetime` integer DEFAULT 0 NOT NULL,
	`tokens_prompt_cached_lifetime` integer DEFAULT 0 NOT NULL,
	`tokens_completion_lifetime` integer DEFAULT 0 NOT NULL,
	`tokens_reasoning_lifetime` integer DEFAULT 0 NOT NULL,
	`cost_lifetime_usd` real DEFAULT 0 NOT NULL,
	`sessions_lifetime` integer DEFAULT 0 NOT NULL,
	`cache_hits_lifetime` integer DEFAULT 0 NOT NULL,
	`analytics_lifetime` text DEFAULT '{}' NOT NULL,
	`usage_24h` text DEFAULT '[]' NOT NULL,
	`usage_7d` text DEFAULT '[]' NOT NULL,
	`usage_30d` text DEFAULT '[]' NOT NULL,
	`usage_12m` text DEFAULT '[]' NOT NULL,
	`by_model` text DEFAULT '{}' NOT NULL,
	`by_provider` text DEFAULT '{}' NOT NULL,
	`by_cli` text DEFAULT '{}' NOT NULL,
	`by_member` text DEFAULT '{}' NOT NULL,
	`by_project` text DEFAULT '{}' NOT NULL,
	`by_org` text DEFAULT '{}' NOT NULL,
	`heatmap_365d` text DEFAULT '{}' NOT NULL,
	`last_synced_at` text,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
